name: Deploy to Google Cloud VM
on:
    push:
        branches:
            - main
            - cloud-deploy
            - feature/devops
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4       

            - name: Copy repo to VM
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VM_IP }}
                username: ${{ secrets.VM_USERNAME }}
                key: ${{ secrets.VM_SSH_KEY }}
                source: "./"
                target: "./myflix-video-catalogue"

            # - name: Execute docker compose in VM
            #   uses: appleboy/ssh-action@master
            #   with:
            #     host: ${{ secrets.VM_IP }}
            #     username: ${{ secrets.VM_USERNAME }}
            #     key: ${{ secrets.VM_SSH_KEY }}
            #     script: |
            #         cd myflix-video-catalogue/src/myflix-video-catalogue
            #         docker-compose up