version: '3'
services:
  web_api:
    build: .
    container_name: video_catalogue
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      - MSSQL_SA_PASSWORD=ILikePink!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"